permalink: pretty
sass:
  style: compressed
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  blanklines: false
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate

title: Trung Nghia Nguyen
author: Trung Nghia Nguyen
email: tn.nguyen@rutgers.edu
# work_url: https://www.math.rutgers.edu/people/department-directory/detail/344-department-directory/2027-nguyen-trung-nghia
orcid_id: 0000-0002-2479-5632
linkedin_username: tnghianguyen
tagline: "A minimal theme for blogs"
description: "Wellcome to my homepage"
url: ""
lang: en

# Optional
# google-tag-manager-id: GTM-xxxxxx
# font-awesome-kit: xxxxxxxxx  # using Font Awesome Kit instead of defining svg icons

paginate: 5

feed:
  posts_limit: 10

navigation:
  - name: Home
    link: /
  - name: Research
    link: /research/
  - name: Teaching
    link: /teaching/

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: post
      category: posts
      toc: true

exclude:
  - Gemfile
  - Rakefile
  - yarn.lock
  - pre-commit
  - /*.json
  - /*.gemspec
  - /*.gem